version: "3.3"

services:
  test-course:
    build:
      context: cpp-course
      dockerfile: Dockerfile
    container_name: test-cpp-course
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    volumes:
      - $MOUNT_PATH/workspace
    ports:
      - "127.0.0.1:2227:22"
