from pathlib import Path

COURSE_NAME = Path(__file__).parent.parent.parent.name

CONTAINER_NAME = COURSE_NAME
CONTAINER_PORT = 2227

HOST_WORKSPACE_DIR = Path(__file__).parent.parent.parent.parent
HOST_COURSE_DIR = HOST_WORKSPACE_DIR / COURSE_NAME
HOST_DOCKER_DIR = HOST_COURSE_DIR / "docker"
HOST_DOCKER_COMPOSE_PATH = HOST_DOCKER_DIR / "docker-compose.yml"

CONTAINER_WORKSPACE_DIR = Path("/workspace")
CONTAINER_COURSE_DIR = CONTAINER_WORKSPACE_DIR / COURSE_NAME
CONTAINER_BASHRC_PATH = CONTAINER_WORKSPACE_DIR / CONTAINER_COURSE_DIR / "docker" / "config" / "bashrc"
