cat <<EOF
Welcome to Docker container!
(___-){
===================================

Type 'exit' to exit =)
EOF

source ~/.bashrc
cd /workspace/test-cpp-course

if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval $(ssh-agent -s) > /dev/null
  ssh-add "/workspace/test-cpp-course/docker/config/keys/gitlab-key" >/dev/null 2>&1
fi
